//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarSyncPlus.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarSyncPlus.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For updates.
        /// </summary>
        public static string AboutView_Button_CheckForUpdate_Content {
            get {
                return ResourceManager.GetString("AboutView_Button_CheckForUpdate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string AboutView_Button_DownloadNow_Content {
            get {
                return ResourceManager.GetString("AboutView_Button_DownloadNow_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a free utility. To report issues/flaws or share appreciation, comments and further suggestions, Please go to the following link..
        /// </summary>
        public static string AboutView_Textblock_BugReportComment {
            get {
                return ResourceManager.GetString("AboutView_Textblock_BugReportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors:.
        /// </summary>
        public static string AboutView_TextBlock_Contributers {
            get {
                return ResourceManager.GetString("AboutView_TextBlock_Contributers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Us: Buy us a coffee/beer.
        /// </summary>
        public static string AboutView_Textblock_SupportUsComment {
            get {
                return ResourceManager.GetString("AboutView_Textblock_SupportUsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on &apos;Help&apos; learn how to use this application..
        /// </summary>
        public static string AboutView_Textblock_UseHelpSuggestionComment {
            get {
                return ResourceManager.GetString("AboutView_Textblock_UseHelpSuggestionComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string AdvancedSettingsView_Checkbox_CheckForUpdates_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_Checkbox_CheckForUpdates_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close button minimizes to tray.
        /// </summary>
        public static string AdvancedSettingsView_Checkbox_CloseToSystemTray_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_Checkbox_CloseToSystemTray_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide sync notification.
        /// </summary>
        public static string AdvancedSettingsView_Checkbox_HideSystemTrayNotification_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_Checkbox_HideSystemTrayNotification_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Credential.
        /// </summary>
        public static string AdvancedSettingsView_CheckBox_ProxySettings_UseDefaultCredentials_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_CheckBox_ProxySettings_UseDefaultCredentials_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run CalendarSync+ when computer starts.
        /// </summary>
        public static string AdvancedSettingsView_Checkbox_RunAtStartup_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_Checkbox_RunAtStartup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to automatically check for latest version of this application.
        /// </summary>
        public static string AdvancedSettingsView_ContentControl_CheckForUpdates_Tooltip {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_ContentControl_CheckForUpdates_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to minimize to system tray on closing the window.
        /// </summary>
        public static string AdvancedSettingsView_ContentControl_HelpButtonCloseToSystray_Tooltip {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_ContentControl_HelpButtonCloseToSystray_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to hide system tray tooltip.
        /// </summary>
        public static string AdvancedSettingsView_ContentControl_HelpButtonHideSystrayNotification_Tooltip {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_ContentControl_HelpButtonHideSystrayNotification_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to start CalendarSync+ when computer starts.
        /// </summary>
        public static string AdvancedSettingsView_ContentControl_HelpButtonRunAtStartup_Tooltip {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_ContentControl_HelpButtonRunAtStartup_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to configure Synchronization Mode.
        /// </summary>
        public static string AdvancedSettingsView_ContentControl_HelpButtonSynchronizationMode_Tooltip {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_ContentControl_HelpButtonSynchronizationMode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        public static string AdvancedSettingsView_RadioButton_ProxySettings_AutoDetect_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_RadioButton_ProxySettings_AutoDetect_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Proxy Configuration.
        /// </summary>
        public static string AdvancedSettingsView_RadioButton_ProxySettings_ManualProxy_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_RadioButton_ProxySettings_ManualProxy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Proxy.
        /// </summary>
        public static string AdvancedSettingsView_RadioButton_ProxySettings_NoProxy_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_RadioButton_ProxySettings_NoProxy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Synchronization.
        /// </summary>
        public static string AdvancedSettingsView_RadioButton_Synchronization_AutoSync_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_RadioButton_Synchronization_AutoSync_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Synchronization.
        /// </summary>
        public static string AdvancedSettingsView_RadioButton_Synchronization_ManualSync_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_RadioButton_Synchronization_ManualSync_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More advanced features are yet to come ;).
        /// </summary>
        public static string AdvancedSettingsView_TextBlock_MoreFeaturesNote_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_TextBlock_MoreFeaturesNote_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string AdvancedSettingsView_TextBlock_ProxySettings_Domain_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_TextBlock_ProxySettings_Domain_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AdvancedSettingsView_TextBlock_ProxySettings_Password_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_TextBlock_ProxySettings_Password_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Proxy:.
        /// </summary>
        public static string AdvancedSettingsView_TextBlock_ProxySettings_ProxyAddress_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_TextBlock_ProxySettings_ProxyAddress_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port No:.
        /// </summary>
        public static string AdvancedSettingsView_TextBlock_ProxySettings_ProxyPort_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_TextBlock_ProxySettings_ProxyPort_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AdvancedSettingsView_TextBlock_ProxySettings_Username_Content {
            get {
                return ResourceManager.GetString("AdvancedSettingsView_TextBlock_ProxySettings_Username_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Account.
        /// </summary>
        public static string GoogleSettingsView_Button_DisconnectAccount_Content {
            get {
                return ResourceManager.GetString("GoogleSettingsView_Button_DisconnectAccount_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Google Calendars.
        /// </summary>
        public static string GoogleSettingsView_Button_GetCalendar_Content {
            get {
                return ResourceManager.GetString("GoogleSettingsView_Button_GetCalendar_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Google Account.
        /// </summary>
        public static string GoogleSettingsView_Button_NewtAccount_Content {
            get {
                return ResourceManager.GetString("GoogleSettingsView_Button_NewtAccount_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Google Calendar.
        /// </summary>
        public static string GoogleSettingsView_Button_ResetCalendar_Content {
            get {
                return ResourceManager.GetString("GoogleSettingsView_Button_ResetCalendar_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Google Calendar.
        /// </summary>
        public static string GoogleSettingsView_GroupBox_Header {
            get {
                return ResourceManager.GetString("GoogleSettingsView_GroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account.
        /// </summary>
        public static string GoogleSettingsView_TextBlock_SelectAccount_Text {
            get {
                return ResourceManager.GetString("GoogleSettingsView_TextBlock_SelectAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Calendar.
        /// </summary>
        public static string GoogleSettingsView_TextBlock_SelectCalendar_Text {
            get {
                return ResourceManager.GetString("GoogleSettingsView_TextBlock_SelectCalendar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Periodic Sync.
        /// </summary>
        public static string HomeView_Button_StartSync_Content_Start {
            get {
                return ResourceManager.GetString("HomeView_Button_StartSync_Content_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Periodic Sync.
        /// </summary>
        public static string HomeView_Button_StartSync_Content_Stop {
            get {
                return ResourceManager.GetString("HomeView_Button_StartSync_Content_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Now.
        /// </summary>
        public static string HomeView_Button_SyncNow_Content {
            get {
                return ResourceManager.GetString("HomeView_Button_SyncNow_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ManageProfileView_Button_New_Content {
            get {
                return ResourceManager.GetString("ManageProfileView_Button_New_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ManageProfileView_DataGrid_Column_DeleteColumn_Header {
            get {
                return ResourceManager.GetString("ManageProfileView_DataGrid_Column_DeleteColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ManageProfileView_DataGrid_Column_NameColumn_Header {
            get {
                return ResourceManager.GetString("ManageProfileView_DataGrid_Column_NameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string ManageProfileView_DataGrid_Column_SyncColumn_Header {
            get {
                return ResourceManager.GetString("ManageProfileView_DataGrid_Column_SyncColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Calendar Profiles.
        /// </summary>
        public static string ManageProfileView_GroupBox_Header {
            get {
                return ResourceManager.GetString("ManageProfileView_GroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Category To Appointments.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_Category_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_Category_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachments.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttachments_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttachments_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attendees.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendees_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendees_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to add attendees to appointment.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendees_ToolTip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendees_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attendees to Description.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendeesDescription_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendeesDescription_C" +
                        "ontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to add attendees to appointment description instead of TO/CC/BCC fields.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendeesDescription_ToolTip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddAttendeesDescription_T" +
                        "oolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Description.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddDescription_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddDescription_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to add description to the calendarAppointments.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddDescription_ToolTip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddDescription_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add events with no recipients as appointments.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddEventsAsAppointment_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddEventsAsAppointment_Co" +
                        "ntent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to add events from Google without recipients as appointments in outlook..
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddEventsAsAppointment_ToolTip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddEventsAsAppointment_To" +
                        "olTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option to add reminders of the appointment. Note: Outlook gives default reminder messages for all calendarAppointments. To disable please go to your outlook settings..
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddReminder_ToolTip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddReminder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reminders.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddReminders_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_DestinationCalendarOptions_AddReminders_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm on Delete.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_OtherOptions_ConfirmDelete_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_OtherOptions_ConfirmDelete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Confirm Dialog before deleting an Appointement.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_OtherOptions_ConfirmDelete_ToolTip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_OtherOptions_ConfirmDelete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Delete.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_OtherOptions_DisableDelete_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_OtherOptions_DisableDelete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Delete when Syncing Calendars.
        /// </summary>
        public static string OptionsSettingsView_CheckBox_OtherOptions_DisableDelete_ToolTip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_OtherOptions_DisableDelete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Last Modified Version (For Bidirectional only).
        /// </summary>
        public static string OptionsSettingsView_CheckBox_OtherOptions_KeepLastModified_Content {
            get {
                return ResourceManager.GetString("OptionsSettingsView_CheckBox_OtherOptions_KeepLastModified_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string OptionsSettingsView_GroupBox_Category_Header {
            get {
                return ResourceManager.GetString("OptionsSettingsView_GroupBox_Category_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Calendar Entry Options.
        /// </summary>
        public static string OptionsSettingsView_GroupBox_DestinationCalendarOptions_Header {
            get {
                return ResourceManager.GetString("OptionsSettingsView_GroupBox_DestinationCalendarOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OptionsSettingsView_GroupBox_OtherOptions_Header {
            get {
                return ResourceManager.GetString("OptionsSettingsView_GroupBox_OtherOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help text here.
        /// </summary>
        public static string OptionsSettingsView_HelpButton_Category_Tooltip {
            get {
                return ResourceManager.GetString("OptionsSettingsView_HelpButton_Category_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Settings.
        /// </summary>
        public static string OutlookSettingsView_Button_ExchnageSettings_DetectSettings_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_Button_ExchnageSettings_DetectSettings_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Exchange Calendar.
        /// </summary>
        public static string OutlookSettingsView_Button_ExchnageSettings_ResetExchangeCalendar_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_Button_ExchnageSettings_ResetExchangeCalendar_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Outlook Calendar.
        /// </summary>
        public static string OutlookSettingsView_Button_OutlookProfileSettings_ResetOutlookCalendar_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_Button_OutlookProfileSettings_ResetOutlookCalendar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Web Services.
        /// </summary>
        public static string OutlookSettingsView_CheckBox_OutlookSettings_EWS_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_CheckBox_OutlookSettings_EWS_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook Application.
        /// </summary>
        public static string OutlookSettingsView_CheckBox_OutlookSettings_OutlookApplicaiton_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_CheckBox_OutlookSettings_OutlookApplicaiton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Server Settings.
        /// </summary>
        public static string OutlookSettingsView_GroupBox_ExchnageSettings_Header {
            get {
                return ResourceManager.GetString("OutlookSettingsView_GroupBox_ExchnageSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &amp;amp; MailBox Settings.
        /// </summary>
        public static string OutlookSettingsView_GroupBox_OutlookProfileSettings_Header {
            get {
                return ResourceManager.GetString("OutlookSettingsView_GroupBox_OutlookProfileSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook Settings.
        /// </summary>
        public static string OutlookSettingsView_GroupBox_OutlookSettings_Header {
            get {
                return ResourceManager.GetString("OutlookSettingsView_GroupBox_OutlookSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Another MailBox.
        /// </summary>
        public static string OutlookSettingsView_RadioButton_OutlookProfileSettings_ChooseAnotherMailBox_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_RadioButton_OutlookProfileSettings_ChooseAnotherMailBox_Conte" +
                        "nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Profile.
        /// </summary>
        public static string OutlookSettingsView_RadioButton_OutlookProfileSettings_ChooseProfile_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_RadioButton_OutlookProfileSettings_ChooseProfile_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default MailBox and Calendar.
        /// </summary>
        public static string OutlookSettingsView_RadioButton_OutlookProfileSettings_DefaultMailnCalendar_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_RadioButton_OutlookProfileSettings_DefaultMailnCalendar_Conte" +
                        "nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Profile.
        /// </summary>
        public static string OutlookSettingsView_RadioButton_OutlookProfileSettings_DefaultProfile_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_RadioButton_OutlookProfileSettings_DefaultProfile_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        public static string OutlookSettingsView_RadioButton_OutlookProfileSettings_SelectProfile_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_RadioButton_OutlookProfileSettings_SelectProfile_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_ExchnageSettings_Domain_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_ExchnageSettings_Domain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_ExchnageSettings_Password_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_ExchnageSettings_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Calendar.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_ExchnageSettings_SelectCalendar_Content {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_ExchnageSettings_SelectCalendar_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Server Url.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_ExchnageSettings_ServerUrl_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_ExchnageSettings_ServerUrl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_ExchnageSettings_UserName_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_ExchnageSettings_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_OutlookProfileSettings_ChooseProfile_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_OutlookProfileSettings_ChooseProfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Calendar.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_OutlookProfileSettings_SelectCalendar_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_OutlookProfileSettings_SelectCalendar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select MailBox.
        /// </summary>
        public static string OutlookSettingsView_TextBlock_OutlookProfileSettings_SelectMailBox_Text {
            get {
                return ResourceManager.GetString("OutlookSettingsView_TextBlock_OutlookProfileSettings_SelectMailBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sync Profile.
        /// </summary>
        public static string ProfileSettingsView_GroupBox_SyncProfile_Header {
            get {
                return ResourceManager.GetString("ProfileSettingsView_GroupBox_SyncProfile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string ProfileSettingsView_TabItem_Google_Header {
            get {
                return ResourceManager.GetString("ProfileSettingsView_TabItem_Google_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ProfileSettingsView_TabItem_Options_Header {
            get {
                return ResourceManager.GetString("ProfileSettingsView_TabItem_Options_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook.
        /// </summary>
        public static string ProfileSettingsView_TabItem_Outlook_Header {
            get {
                return ResourceManager.GetString("ProfileSettingsView_TabItem_Outlook_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string ProfileSettingsView_TabItem_Sync_Header {
            get {
                return ResourceManager.GetString("ProfileSettingsView_TabItem_Sync_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        public static string ProfileSettingsView_TextBlock_SelectProfile_Text {
            get {
                return ResourceManager.GetString("ProfileSettingsView_TextBlock_SelectProfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SettingsView_Button_Save_Content {
            get {
                return ResourceManager.GetString("SettingsView_Button_Save_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string SettingsView_TabItem_Application_Header {
            get {
                return ResourceManager.GetString("SettingsView_TabItem_Application_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars.
        /// </summary>
        public static string SettingsView_TabItem_Calendars_Header {
            get {
                return ResourceManager.GetString("SettingsView_TabItem_Calendars_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string SettingsView_TabItem_Manage_Header {
            get {
                return ResourceManager.GetString("SettingsView_TabItem_Manage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ShellView_AboutButton_Content {
            get {
                return ResourceManager.GetString("ShellView_AboutButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Calendar Sync +.
        /// </summary>
        public static string ShellView_AboutButton_ToolTip {
            get {
                return ResourceManager.GetString("ShellView_AboutButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ShellView_ExitButton_Content {
            get {
                return ResourceManager.GetString("ShellView_ExitButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string ShellView_ExitButton_ToolTip {
            get {
                return ResourceManager.GetString("ShellView_ExitButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ShellView_Flyouts_About_Header {
            get {
                return ResourceManager.GetString("ShellView_Flyouts_About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ShellView_Flyouts_Help_Header {
            get {
                return ResourceManager.GetString("ShellView_Flyouts_Help_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string ShellView_Flyouts_Settings_Header {
            get {
                return ResourceManager.GetString("ShellView_Flyouts_Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ShellView_HelpButton_Content {
            get {
                return ResourceManager.GetString("ShellView_HelpButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ShellView_HelpButton_ToolTip {
            get {
                return ResourceManager.GetString("ShellView_HelpButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available for download.
        /// </summary>
        public static string ShellView_RightWindowCommands_Download_Tooltip {
            get {
                return ResourceManager.GetString("ShellView_RightWindowCommands_Download_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string ShellView_SettingsButton_Content {
            get {
                return ResourceManager.GetString("ShellView_SettingsButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Calendar Sync +.
        /// </summary>
        public static string ShellView_SettingsButton_ToolTip {
            get {
                return ResourceManager.GetString("ShellView_SettingsButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Sync +.
        /// </summary>
        public static string ShellView_Window_Title {
            get {
                return ResourceManager.GetString("ShellView_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SystemtrayNotifierView_MenuItem_TaskBarIcon_ExitApplicaiton_Header {
            get {
                return ResourceManager.GetString("SystemtrayNotifierView_MenuItem_TaskBarIcon_ExitApplicaiton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        public static string SystemtrayNotifierView_MenuItem_TaskBarIcon_ShowWindowMessage_Header {
            get {
                return ResourceManager.GetString("SystemtrayNotifierView_MenuItem_TaskBarIcon_ShowWindowMessage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to maximize the application..
        /// </summary>
        public static string SystemtrayNotifierView_TextBlock_TaskBarIcon_MaximizeMessage_ToolTip {
            get {
                return ResourceManager.GetString("SystemtrayNotifierView_TextBlock_TaskBarIcon_MaximizeMessage_ToolTip", resourceCulture);
            }
        }
    }
}
